// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqHgP2ZUZVavoSpQzyE0DSOJRTIv4lD64',
    appId: '1:552876095542:android:6403cae2a3e3a4c5430097',
    messagingSenderId: '552876095542',
    projectId: 'flutter-chat-a4a04',
    storageBucket: 'flutter-chat-a4a04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7yFUZhpb4OwPncMLGEaAxKHJLuz0wJ8Q',
    appId: '1:552876095542:ios:096032b8c9563887430097',
    messagingSenderId: '552876095542',
    projectId: 'flutter-chat-a4a04',
    storageBucket: 'flutter-chat-a4a04.appspot.com',
    androidClientId: '552876095542-a593rs7s9v65ta2sgo1rothvgrd3h68v.apps.googleusercontent.com',
    iosClientId: '552876095542-ikfjdpl262aoopipshr1c23mpne08n5e.apps.googleusercontent.com',
    iosBundleId: 'com.chats.chats',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4shzYAPwMh9RlJJc7t1bbVRgSsRBfb08',
    appId: '1:552876095542:web:f0c6587a525c0198430097',
    messagingSenderId: '552876095542',
    projectId: 'flutter-chat-a4a04',
    authDomain: 'flutter-chat-a4a04.firebaseapp.com',
    storageBucket: 'flutter-chat-a4a04.appspot.com',
    measurementId: 'G-K73GNKHEYC',
  );

}